In [1]:
# This is an intro to Numpy

In [2]:
# A large part of Data Science is array and matrix based

In [3]:
# This lesson will show me how to creare arrays in Numpy

In [4]:
import numpy as np

In [39]:
# I can convert a list to an array
my_list1 = [1,2,3,4]
my_array1 = np.array(my_list1)
my_array1

array([1, 2, 3, 4])

In [20]:
my_list2 =[4,5,6,7]

In [21]:
my_lists = [my_list1,my_list2]

In [23]:
my_array2 = np.array(my_lists)

In [24]:
my_array2

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [28]:
my_list3 = [7,8,9,1]

In [29]:
my_array3 = np.array(my_list3)

In [30]:
my_array2.shape

(2, 4)

In [32]:
my_array4 = my_array3 + my_array2

In [33]:
my_array4.dtype

dtype('int64')

In [36]:
# if I want to build an empty array of zeros follow the following
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [44]:
# a special case of arrays is the array of ones
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [45]:
# Make an empty matrix
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [46]:
# Make an identity matrix
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [47]:
# With NP Arrange I can build an array with a start value, end value, and step fund for evenly spaced values
np.arange(1, 20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])