In [1]:
import numpy as np

In [3]:
5 / 2

2.5

In [7]:
# Create an array by making a list of 2 sublists
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

In [8]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [9]:
# This is scalar opertation or matrix algebra
arr1 * arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [10]:
# Indexing arrays
arr2 = np.arange(0,11) 

In [11]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr2[8]

8

In [13]:
arr2[1:5]

array([1, 2, 3, 4])

In [14]:
arr2[0:5]

array([0, 1, 2, 3, 4])

In [15]:
# Setting Values from an index range
arr2[0:5] = 100

In [16]:
arr2

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
arr2 = np.arange(0,11)

In [18]:
# I can take a slice of an array
slicey = arr2[0:6]

In [19]:
slicey

array([0, 1, 2, 3, 4, 5])

In [20]:
# With a colon I can set all the elements of an array to something
slicey[:] = 100

In [21]:
slicey

array([100, 100, 100, 100, 100, 100])

In [23]:
# note when I slice an array unless I make a copy the sliced changes will effect the original array
arr2

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [24]:
# to build a copy I must be explicit
arr2_copy = arr2.copy()